# Generated by Django 3.2.5 on 2021-12-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='club_member',
            new_name='club_own',
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.CharField(default='', max_length=520),
        ),
    ]
