# Generated by Django 3.2.5 on 2021-12-01 14:31

import clubs.user_types
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20211201_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'CLUB_OWNER'), (2, 'OFFICER'), (3, 'MEMBER'), (4, 'APPLICANT')], default=clubs.user_types.UserTypes['APPLICANT'], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
