# Generated by Django 3.2.5 on 2021-12-01 14:53

import clubs.user_types
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_member_user_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(condition=models.Q(('user_type', clubs.user_types.UserTypes['CLUB_OWNER'])), fields=('club_membership',), name="there can't exist more than one club owner"),
        ),
    ]
