# Generated by Django 3.2.5 on 2021-12-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', "0004_member_there can't exist more than one club owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='club',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
