# Generated by Django 3.2.5 on 2021-12-04 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_member_unique_together'),
        ('clubs', '0005_auto_20211201_1759'),
    ]

    operations = [
    ]
